{
 "title": "Weather",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    { "expr": "weather_temp_kuchyne", "legendFormat": "kuchyne" },
    { "expr": "weather_temp_terasa", "legendFormat": "terasa" }
   ]
  },
  {
   "title": "Barometric pressure at sea level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pressurehpa", "label": "hPa" }
   ],
   "targets": [
    { "expr": "pressure_sea_level_hpa" }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "co2_ppm" }
   ]
  },
  {
   "title": "Outside temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "targets": [
    { "expr": "weather_temp_terasa" }
   ]
  },
  {
   "title": "Inside temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "targets": [
    { "expr": "weather_temp_kuchyne" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "humidity_pct" }
   ]
  },
  {
   "title": "Air particles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "expr": "pm25{measurement=~\"particles.*\"}"
    }
   ]
  }
 ]
}