{
 "title": "system",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Load in 1,5,15 minute averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "free RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "free" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "CPU temperatures (5m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg_over_time(CPU_temp_pi[5m])", "legendFormat": "pihole" },
    {
     "expr": "avg_over_time(CPU_temp_weather[5m])",
     "legendFormat": "weather"
    },
    {
     "expr": "avg_over_time(CPU_temp_docker[5m])",
     "legendFormat": "dockerpi"
    }
   ]
  },
  {
   "title": "/dev/root free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/root\"}"
    }
   ]
  }
 ]
}